project:
  name: quickstart-jfrog-container-registry
  owner: quickstart-eng@amazon.com
  s3_object_acl: public-read
  # lambda_source_path: submodules/quickstart-jfrog-artifactory/submodules/quickstart-amazon-eks/functions/source
  # lambda_zip_path: submodules/quickstart-jfrog-artifactory/submodules/quickstart-amazon-eks/functions/packages
  s3_object_acl: public-read
  s3_regional_buckets: True
  s3_bucket: tcat-34c17b83dcbd547393a86d8053a8d298  # commercial accounts
  regions:
    - us-east-1

tests:
  # jfrog-container-registry-ec2:
  #   parameters:
  #     KeyPairName: "vinaykey1"
  #     AccessCidr: "0.0.0.0/0"
  #     RemoteAccessCidr: "0.0.0.0/0"
  #     JcrVersion: 7.10.2
  #     JcrServerName: "jcr"
  #     SmLicenseCertName: "jfrog-artifactory"
  #     MasterKey: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
  #     KeystorePassword: "$[taskcat_genpass_8A]"
  #     AnsibleVaultPass: "$[taskcat_genpass_8A]"
  #     MultiAzDatabase: "false"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     DatabaseInstance: "db.m5.large"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-container-registry/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"

  #   #   AvailabilityZones: "$[taskcat_genaz_2]"
  #   # template: templates/jfrog-container-registry-ec2-master.template.yaml

  #     AvailabilityZones: "us-east-1a, us-east-1b"
  #     VpcId           : "vpc-0ec1fde903256cbaa"
  #     PublicSubnet1Id : "subnet-0e8b0fd67f9597f8b"
  #     PrivateSubnet1Id: "subnet-082f94c09dc1ff95f"
  #     PublicSubnet2Id : "subnet-0180484a26c72dd11"
  #     PrivateSubnet2Id: "subnet-0879e6c28c7650860"
  #   template: templates/jfrog-container-registry-ec2-existing-vpc.template.yaml

  #   regions:
  #     - us-east-1

  jfrog-container-registry-ecs:
    parameters:
      KeyPairName: "vinaykey1"
      RemoteAccessCidr: "0.0.0.0/0"
      AccessCidr: "0.0.0.0/0"
      DatabasePassword: "$[taskcat_genpass_8A]"
      DatabaseInstance: "db.m5.large"
      JcrVersion: "7.10.5"
      NumberOfSecondary: "2"
      AnsibleVaultPass: "$[taskcat_genpass_8A]"
      JcrServerName: "jcr"
      MasterKey: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
      SmLicenseCertName: "jfrog-artifactory"
      MultiAzDatabase: "false"
      QsS3BucketName: "$[taskcat_autobucket]"
      QsS3KeyPrefix: "quickstart-jfrog-container-registry/"
      QsS3BucketRegion: "$[taskcat_current_region]"

      AvailabilityZones: "$[taskcat_genaz_2]"
    template: templates/jfrog-container-registry-ecs-master.template.yaml

    #   AvailabilityZones: "us-west-1a, us-west-1b"
    #   VpcId           : "vpc-0cfae02bb76f719c3"
    #   PublicSubnet1Id : "subnet-0a9d6fff8e2c35441"
    #   PrivateSubnet1Id: "subnet-06c4724a60b0f8dd9"
    #   PublicSubnet2Id : "subnet-05b23f7310bb6e0c3"
    #   PrivateSubnet2Id: "subnet-0aef068b8ca595bfd"
    # template: templates/jfrog-container-registry-ecs-existing-vpc.template.yaml

    regions:
        - us-east-1

  # jfrog-container-registry-eks:
  #   parameters:
  #     KeyPairName: "$[taskcat_getkeypair]"
  #     RemoteAccessCidr: "10.0.0.0/16"
  #     AccessCidr: "10.0.0.0/16"
  #     AvailabilityZones: "$[taskcat_genaz_3]"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     DatabaseInstance: "db.m5.large"
  #   #  JcrVersion: "7.2.1"
  #     JcrServerName: "artifactory"
  #     MasterKey: "override"
  #     SmLicenseCertName: "override"
  #     MultiAzDatabase: "false"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-container-registry/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #   template: templates/jfrog-container-registry-eks-master.template.yaml
  #   regions:
  #     # - us-east-1
  #     - us-west-2
  #     - us-east-2
  #     - eu-west-1
  #     - eu-west-2
  #     # - eu-west-3
  #     - eu-central-1
